### ISSUE TITLE
Add a domain, validation

### ISSUE THREAD

**Issue by wesley974** [wesley974/mailserv#16]
Actually, we can add "e-solutions.re", and "e-solutions". This last one is wrong, it is not a domain.
Need to have validations : 

A domain need to have an extension : Domain_Name_with_or_without_dot DOT Extension

**Comment by narutosanjiv** [comment]
Hi @wesley974  ,
What do you mean by 'Domain_Name_with_or_without_dot DOT Extension'?.

**Comment by wesley974** [comment]
Hi,

I mean this is possible : info.aise.re(name with dot + .re) ; aise.re
