### ISSUE TITLE
ruby-rrd package is not more maintained

### ISSUE THREAD

**Issue by narutosanjiv** [wesley974/mailserv#2]
Hi @wesley974 ,
We have found that ruby-rrd is not more being maintained, so we will not be using ruby-rrd but still we will using rrdtool(operating system package) for generating. 

We are trying to get rid of rrdtool but it seem that we do not enough choice. We have seen graphite which generate time-numeric series graph, but it does not suit our requirements.

**Comment by narutosanjiv** [comment]
Do you have any suggestion for replacing rrdtool?. If have , please let us know so that we can get rid of rrdtool altogether else i have call system command from ruby to generate graph.

**Comment by wesley974** [comment]
Hi,

There's 'monit' in OpenBSD packages.
If you want to take a look, the project is here : https://mmonit.com/ & https://mmonit.com/monit/

**Comment by wesley974** [comment]
Or try this one : Facette - https://blog.facette.io/2014/09/10/facette-0-2-0-released/

**Comment by narutosanjiv** [comment]
@wesley974 Mmonit(https://mmonit.com) seem to be good to start. You have suggested other tool as well as. I am seeing collectd to collect data.

**Comment by wesley974** [comment]
Riemann tool could be also a good start. (it use Ruby)
see : http://riemann.io/howto.html#measure-cpu-memory-and-disk-use

**Comment by wesley974** [comment]
We ll use Munin.

The project : http://munin-monitoring.org/
The source : https://github.com/munin-monitoring/munin
API : http://munin-monitoring.org/wiki/RestApi
